/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista.Factura;

import ec.edu.ups.controlador.ControladorProducto;
import ec.edu.ups.controlador.FCabeceraControlador;
import ec.edu.ups.controlador.FDetalleControlador;
import ec.edu.ups.controlador.PersonaControlador;
import ec.edu.ups.modelo.FCabecera;
import ec.edu.ups.modelo.FDetalle;
import ec.edu.ups.modelo.Personas;
import ec.edu.ups.modelo.Producto;
import ec.edu.ups.personas.CrearPersonas;
import ec.edu.ups.vista.Principal.Empleado;
import java.awt.event.KeyEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ByronPC
 */
public class CrearFac extends javax.swing.JInternalFrame {
 public static String x;
    /**
     * Creates new form NewJInternalFramepublic static String x; private
     * FCabeceraControlador fCabeceraControlador;
     */

    String url = "jdbc:oracle:thin:@localhost:1521:orcl";
    String user = "BaseFarmacia";
    String password = "bf123";

    //private Date fecha;
    private int contador;
    private double totalCP, subtotal, iva, ivaPro, total, a;
    private DefaultTableModel tablaF;

    //clases
    private Personas per;
    private Producto pro;
    private FCabecera fcab;
    private FDetalle fdet;
    private FCabeceraControlador ContFCab = new FCabeceraControlador(url, user, password);
    private FDetalleControlador ContFDetalle = new FDetalleControlador(url, user, password);
    private PersonaControlador personaControlador = new PersonaControlador(url, user, password);
    private ControladorProducto contPro = new ControladorProducto(url, user, password);
     public static String fechaActual() {

        Date fecha = new Date();
        SimpleDateFormat formatoFecha = new SimpleDateFormat("dd/MM/YYY");
        return formatoFecha.format(fecha);

    }

    /**
     * Creates new form CrearFac
     */
    public CrearFac(FCabeceraControlador fCabeceraControlador) {
        initComponents();
        this.fcab = new FCabecera();

        totalCP = 0;
        subtotal = 0;
        iva = 0;
        total = 0;
        tablaF = null;
        pro = null;
        contador = 0;
        ivaPro = 0;
        a = 0;

        x = "x";
        int a = Empleado.desktop.getWidth() - this.getWidth();
        int b = Empleado.desktop.getHeight() - this.getHeight();

        setLocation(a / 2, b / 2);
        setVisible(true);

        //fecha actual 
        txtFecha.setText(fechaActual());
        //ruc 
        int ruc = ContFCab.buscarUltimoCodigo() + 1;
        txtRuc.setText(String.valueOf(ruc));
        //estado factura
        txtEstado.setText("T");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblRuc = new javax.swing.JLabel();
        txtRuc = new javax.swing.JTextField();
        lblFecha = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        lblCedC5 = new javax.swing.JLabel();
        txtCedC = new javax.swing.JTextField();
        btnBuscarCF = new javax.swing.JButton();
        lblNomC5 = new javax.swing.JLabel();
        txtNomC = new javax.swing.JTextField();
        lblTelC5 = new javax.swing.JLabel();
        txtTelC = new javax.swing.JTextField();
        txtApeC = new javax.swing.JTextField();
        lblApeC5 = new javax.swing.JLabel();
        lblDirC5 = new javax.swing.JLabel();
        txtDirC = new javax.swing.JTextField();
        lblCodC7 = new javax.swing.JLabel();
        txtNomPro = new javax.swing.JTextField();
        btbnBusPro = new javax.swing.JButton();
        lblCodC8 = new javax.swing.JLabel();
        txtCodPro = new javax.swing.JTextField();
        lblCodC6 = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblServF = new javax.swing.JTable();
        txtSubtotal = new javax.swing.JTextField();
        lblSub = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        txtIva = new javax.swing.JTextField();
        lblTot = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        lblCedC6 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnCrear = new javax.swing.JButton();
        btnCancelarF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lblTitulo.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        lblTitulo.setText("Crear Factura");

        lblRuc.setBackground(new java.awt.Color(255, 255, 255));
        lblRuc.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblRuc.setText("RUC Factura");

        txtRuc.setEditable(false);
        txtRuc.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtRuc.setEnabled(false);

        lblFecha.setBackground(new java.awt.Color(255, 255, 255));
        lblFecha.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblFecha.setText("Fecha");

        txtFecha.setEditable(false);
        txtFecha.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtFecha.setEnabled(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblCedC5.setBackground(new java.awt.Color(255, 255, 255));
        lblCedC5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblCedC5.setText("Cedula Cliente");

        txtCedC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        btnBuscarCF.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnBuscarCF.setText("Buscar");
        btnBuscarCF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCFActionPerformed(evt);
            }
        });

        lblNomC5.setBackground(new java.awt.Color(255, 255, 255));
        lblNomC5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblNomC5.setText("Nombre Cliente");

        txtNomC.setEditable(false);
        txtNomC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtNomC.setEnabled(false);

        lblTelC5.setBackground(new java.awt.Color(255, 255, 255));
        lblTelC5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblTelC5.setText("Telefono Cliente");

        txtTelC.setEditable(false);
        txtTelC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTelC.setEnabled(false);

        txtApeC.setEditable(false);
        txtApeC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtApeC.setEnabled(false);

        lblApeC5.setBackground(new java.awt.Color(255, 255, 255));
        lblApeC5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblApeC5.setText("Apellido Cliente");

        lblDirC5.setBackground(new java.awt.Color(255, 255, 255));
        lblDirC5.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblDirC5.setText("Direccion Cliente");

        txtDirC.setEditable(false);
        txtDirC.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtDirC.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lblCedC5)
                        .addGap(18, 18, 18)
                        .addComponent(txtCedC, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCF)
                        .addGap(129, 129, 129))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblNomC5)
                                .addGap(18, 18, 18)
                                .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblTelC5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelC, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblApeC5)
                            .addComponent(lblDirC5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDirC, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                            .addComponent(txtApeC)))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedC5)
                    .addComponent(txtCedC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblApeC5)
                        .addComponent(txtApeC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNomC5)
                        .addComponent(txtNomC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDirC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTelC5)
                        .addComponent(txtTelC, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblDirC5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblCodC7.setBackground(new java.awt.Color(255, 255, 255));
        lblCodC7.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblCodC7.setText("Nombre:");

        txtNomPro.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N

        btbnBusPro.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btbnBusPro.setText("Buscar");
        btbnBusPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbnBusProActionPerformed(evt);
            }
        });

        lblCodC8.setBackground(new java.awt.Color(255, 255, 255));
        lblCodC8.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblCodC8.setText("Codigo:");

        txtCodPro.setEditable(false);
        txtCodPro.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtCodPro.setEnabled(false);

        lblCodC6.setBackground(new java.awt.Color(255, 255, 255));
        lblCodC6.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblCodC6.setText("Stock");

        txtStock.setEditable(false);
        txtStock.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtStock.setEnabled(false);

        tblServF.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, "0", null, null, null, null}
            },
            new String [] {
                "codigo", "cantidad", "nombre", "precio u", "IvaProducto", "totalIP"
            }
        ));
        tblServF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblServFKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tblServF);

        txtSubtotal.setEditable(false);
        txtSubtotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtSubtotal.setEnabled(false);
        txtSubtotal.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                txtSubtotalPropertyChange(evt);
            }
        });

        lblSub.setBackground(new java.awt.Color(255, 255, 255));
        lblSub.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblSub.setText("Subtotal");

        lblIva.setBackground(new java.awt.Color(255, 255, 255));
        lblIva.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblIva.setText("I.V.A");

        txtIva.setEditable(false);
        txtIva.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtIva.setEnabled(false);

        lblTot.setBackground(new java.awt.Color(255, 255, 255));
        lblTot.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblTot.setText("Total");

        txtTotal.setEditable(false);
        txtTotal.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtTotal.setEnabled(false);

        lblCedC6.setBackground(new java.awt.Color(255, 255, 255));
        lblCedC6.setFont(new java.awt.Font("Sitka Small", 1, 18)); // NOI18N
        lblCedC6.setText("Estado Factura");

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        txtEstado.setEnabled(false);

        btnCrear.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCrear.setText("Crear");
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        btnCancelarF.setFont(new java.awt.Font("Cambria Math", 1, 14)); // NOI18N
        btnCancelarF.setText("Cancelar");
        btnCancelarF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarFActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Registrar Cliente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCedC6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCrear)
                        .addGap(34, 34, 34)
                        .addComponent(btnCancelarF)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblSub)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblIva)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblTot)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(2, 2, 2)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 703, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(266, 266, 266)
                            .addComponent(lblTitulo))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(147, 147, 147)
                            .addComponent(lblRuc)
                            .addGap(18, 18, 18)
                            .addComponent(txtRuc, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblFecha)
                            .addGap(18, 18, 18)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblCodC7)
                            .addGap(18, 18, 18)
                            .addComponent(txtNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btbnBusPro)
                            .addGap(27, 27, 27)
                            .addComponent(lblCodC8)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblCodC6)
                            .addGap(18, 18, 18)
                            .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtRuc)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFecha)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRuc)
                            .addComponent(lblFecha))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodC6)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodC7)
                    .addComponent(txtNomPro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodC8)
                    .addComponent(txtCodPro, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btbnBusPro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSub)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIva)
                    .addComponent(txtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTot)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCedC6)
                    .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrear)
                    .addComponent(btnCancelarF))
                .addGap(83, 83, 83))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarCFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCFActionPerformed

        PersonaControlador cp = new PersonaControlador(url, user, password);
        Personas p = new Personas();
        p = cp.BuscaarPersona(txtCedC.getText());
        if (p.getCedula() != null) {
            txtNomC.setText(p.getNombres());
            txtApeC.setText(p.getApellidos());
            txtDirC.setText(p.getDireccion());
            txtTelC.setText(p.getTelefono());
            // txtrol.setText(String.valueOf(p.getRol_id()));
        } else {
            JOptionPane.showMessageDialog(this, "La cedula ingresada no está registrada", "Buscar cédula de persona", JOptionPane.OK_OPTION);
        }
    }//GEN-LAST:event_btnBuscarCFActionPerformed

    private void btbnBusProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbnBusProActionPerformed

        pro = new Producto();
        ControladorProducto pro1 = new ControladorProducto(url, user, password);
        pro = pro1.BuscarNombre(txtNomPro.getText());
        //Producto produ = new Producto();

        if (pro.getNombre() != null) {

            txtCodPro.setText(String.valueOf(pro.getId()));
            txtStock.setText(String.valueOf(pro.getStock()));

        } else {

            JOptionPane.showMessageDialog(this, "El producto ingresado no está registrado", "Buscar Producto", JOptionPane.OK_OPTION);

        }
    }//GEN-LAST:event_btbnBusProActionPerformed

    private void tblServFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblServFKeyReleased

        int key = evt.getKeyCode();
        if (key == KeyEvent.VK_ENTER) {
            int fila = tblServF.getSelectedRow();
            int columna = tblServF.getSelectedColumn();
            int codigoServ = 0;

            Object[] datos1 = {"", 0, "", "", "", "", ""};

            if (columna == 0) {
                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                pro = contPro.Buscar(codigoServ);

                int cant = Integer.parseInt(tblServF.getValueAt(fila, 1).toString());

                tablaF = (DefaultTableModel) tblServF.getModel();
                tablaF.removeRow(fila);

                if (pro.getIva() == 'T') {

                    a = cant * pro.getPrecio();
                    ivaPro = a * 0.12;
                    totalCP = a + ivaPro;

                    Object[] datos = {codigoServ,
                        cant,
                        pro.getNombre(),
                        pro.getPrecio(),
                        ivaPro,
                        totalCP
                    };

                    tablaF.addRow(datos);
                    tablaF.addRow(datos1);

                } else if (pro.getIva() == 'F') {

                    ivaPro = 0;

                    totalCP = cant * pro.getPrecio();

                    Object[] datos = {codigoServ,
                        cant,
                        pro.getNombre(),
                        pro.getPrecio(),
                        ivaPro,
                        totalCP
                    };

                    tablaF.addRow(datos);
                    tablaF.addRow(datos1);
                }

            } else if (columna == 1) {

                codigoServ = Integer.parseInt(tblServF.getValueAt(fila, columna - 1).toString());
                int cant = Integer.parseInt(tblServF.getValueAt(fila, columna).toString());
                tablaF.removeRow(fila);
                tablaF.removeRow(tblServF.getRowCount() - 1);

                if (pro.getIva() == 'T') {

                    a = cant * pro.getPrecio();
                    ivaPro = a * 0.12;
                    totalCP = a + ivaPro;

                    Object[] datos = {codigoServ,
                        cant,
                        pro.getNombre(),
                        pro.getPrecio(),
                        ivaPro,
                        totalCP
                    };

                    tablaF.addRow(datos);
                    tablaF.addRow(datos1);

                } else if (pro.getIva() == 'F') {

                    ivaPro = 0;
                    totalCP = cant * pro.getPrecio();

                    Object[] datos = {codigoServ,
                        cant,
                        pro.getNombre(),
                        pro.getPrecio(),
                        ivaPro,
                        totalCP
                    };

                    tablaF.addRow(datos);
                    tablaF.addRow(datos1);
                }

            }

            subtotal = subtotal + totalCP;
            txtSubtotal.setText(String.valueOf(subtotal));

            iva = subtotal * 0.12;
            txtIva.setText(String.valueOf(iva));

            total = subtotal + iva;
            txtTotal.setText(String.valueOf(total));

            float pv = 0, pc = 0, pg;
            pv = Float.parseFloat(txtSubtotal.getText());
            pc = Float.parseFloat(txtIva.getText());
            pg = Float.parseFloat(txtTotal.getText());

            txtSubtotal.setText(String.format(Locale.US, "%.2f", pv));
            txtIva.setText(String.format(Locale.US, "%.2f", pc));
            txtTotal.setText(String.format(Locale.US, "%.2f", pg));

        }
    }//GEN-LAST:event_tblServFKeyReleased

    private void txtSubtotalPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_txtSubtotalPropertyChange

    }//GEN-LAST:event_txtSubtotalPropertyChange

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        String cedulaC = txtCedC.getText();
        per = personaControlador.BuscaarPersona(cedulaC);

        //facDetalle

        llenarDatos();
         String fecha = txtFecha.getText();
        //SimpleDateFormat sf = new SimpleDateFormat("dd/MM/yyyy");
        /*Date f = null;
        try {
            f = sf.parse(fecha);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }*/
        fcab.setFecha(fecha);

        //factura
        //agregarDatos Factura Cabecera
        fcab.setId(Integer.parseInt(txtRuc.getText()));
        fcab.setSubtotal(subtotal);
        fcab.setIva(iva);
        fcab.setTotal(total);
        String est = txtEstado.getText();
        fcab.setEstado(est.charAt(0));
        fcab.setPer(per);
        ContFCab.createFacCab(fcab);

        JOptionPane.showMessageDialog(this, "Factura Creada");
        System.out.println("Factura Cabecera \n" + fcab.toString());

        for (int i = 0; i < tblServF.getRowCount() - 1; i++) {

            System.out.println("i " + i);
            fdet = new FDetalle();

            double cant = Integer.parseInt(tblServF.getValueAt(i, 1).toString());
            int cant1 = (int) cant;
            int ruc1 = Integer.parseInt(txtRuc.getText());
            int codigo = ContFDetalle.buscarUltCodigo() + (i + 1);

            double cod = Integer.parseInt(tblServF.getValueAt(i, 0).toString());
            int cod1 = (int) cod;

            //Agregar Datos Factura Detalle
            fdet.setId(codigo);
            fdet.setCant(cant1);
            fdet.setPrecioUnitario(Double.parseDouble(tblServF.getValueAt(i, 3).toString()));
            fdet.setIvaPro(ivaPro);
            fdet.setTotalCP(totalCP);
            fdet.setRucFac(ruc1);
            fdet.setCodPro(cod1);

            fcab.añadirFacDetalle(fdet);
            ContFDetalle.createFacDet(fdet);
            System.out.println("Factura Detalle \n " + fdet.toString());

        }

        int ruc = ContFCab.buscarUltimoCodigo() + 1;
        txtRuc.setText(String.valueOf(ruc));
        contador = 0;

        vaciarDatos();
        vaciarTabla();
        
        dispose();


    }//GEN-LAST:event_btnCrearActionPerformed
 public void llenarDatos() {

         DefaultTableModel modeloP = (DefaultTableModel) tblServF.getModel();
        List<FDetalle> lista = fcab.getDetalle();

        while (contador < lista.size()) {

            Object[] datos3 = {fcab.getDetalle().get(contador).getId(),
                lista.get(contador).getCant(),
                lista.get(contador).getPro().getNombre(),
                lista.get(contador).getPro().getPrecio(),
                lista.get(contador).getIvaPro(),
                lista.get(contador).getTotalCP()
            };

            modeloP.addRow(datos3);
            contador++;

        }

    }
//vaciar datos de la tabla
    public void vaciarTabla() {

        DefaultTableModel modelo = (DefaultTableModel) tblServF.getModel();
        int filas = tblServF.getRowCount();
        for (int i = 0; i < filas; i++) {

            modelo.removeRow(0);

        }

        Object[] datos1 = {"", 0, "", "", "", ""};
        tablaF.addRow(datos1);
    }

    //vaciar datos
    public void vaciarDatos() {

        txtApeC.setText("");
        txtCedC.setText("");
        txtCodPro.setText("");
        txtDirC.setText("");
        txtIva.setText("");
        txtNomC.setText("");
        txtNomPro.setText("");
        txtStock.setText("");
        txtSubtotal.setText("");
        txtTelC.setText("");
        txtTotal.setText("");

    }

    private void btnCancelarFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarFActionPerformed

        x = null;
        this.dispose();
    }//GEN-LAST:event_btnCancelarFActionPerformed

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        x=null;
    }//GEN-LAST:event_formInternalFrameClosing

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         CrearPersonas ven4= new CrearPersonas(personaControlador);
        Empleado.desktop.add(ven4);
        ven4.toFront();
        ven4.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btbnBusPro;
    private javax.swing.JButton btnBuscarCF;
    private javax.swing.JButton btnCancelarF;
    private javax.swing.JButton btnCrear;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblApeC5;
    private javax.swing.JLabel lblCedC5;
    private javax.swing.JLabel lblCedC6;
    private javax.swing.JLabel lblCodC6;
    private javax.swing.JLabel lblCodC7;
    private javax.swing.JLabel lblCodC8;
    private javax.swing.JLabel lblDirC5;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblNomC5;
    private javax.swing.JLabel lblRuc;
    private javax.swing.JLabel lblSub;
    private javax.swing.JLabel lblTelC5;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTot;
    private javax.swing.JTable tblServF;
    private javax.swing.JTextField txtApeC;
    private javax.swing.JTextField txtCedC;
    private javax.swing.JTextField txtCodPro;
    private javax.swing.JTextField txtDirC;
    private javax.swing.JTextField txtEstado;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtIva;
    private javax.swing.JTextField txtNomC;
    private javax.swing.JTextField txtNomPro;
    private javax.swing.JTextField txtRuc;
    private javax.swing.JTextField txtStock;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtTelC;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
