--CREACION DE SECUENCIAS 
--SECUENCIA EN LA TABLA CATEGORIAS
CREATE SEQUENCE HIP_CATEGORIAS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA FACTURADETALLES
CREATE SEQUENCE HIP_FACTURA_CABECERAS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA FACTURASCABECERAS
CREATE SEQUENCE HIP_FACTURA_DETALLES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA MEDIDAD
CREATE SEQUENCE HIP_MEDIDAS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA PERSONAS
CREATE SEQUENCE HIP_PERSONAS_SEQ
START WITH 10
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA PRODUCTOS
CREATE SEQUENCE HIP_PRODUCTOS_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA PROVEEDORPRODUCTO
CREATE SEQUENCE HIP_PROVEEDOR_PRODUCTO_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;

--SECUENCIA EN LA TABLA PROVEEDORES
CREATE SEQUENCE HIP_PROVEEDORES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;


--SECUENCIA EN LA TABLA PROVEEDORPRODUCTO
CREATE SEQUENCE HIP_ROLES_SEQ
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;
COMMIT;



